import { faker } from '@faker-js/faker';

// ----------------------------------------------------------------------

const POST_TITLES = [
  'Timberland Investment: A Promising Opportunity for Diversification',
  'Harnessing Agriculture Farmland as Powerful Measures to Control Inflation',
  'How To Convert Agricultural Land to Commercial Land: A Comprehensive Guide',
  'Understanding Agriculture Land Measurement in India',
  'Coconut Farming in India: Driving Economic Growth, Ensuring Food Security',
  'Cultivating Wealth: The Advantages of Managed Farmland Investments',
  'Importance of Van Mahotsav: A Festival of Environmental Harmony',
  '5 Types of Agricultural Land in India',
  'Agriculture Land Registration Charges - State-wise Stamp Duty Rates',
  'Agricultural Land Reform in India: Various Movements and Measures Taken By the Government.',
  'Decoding Capital Gains On The Sale Of Agricultural Land in India',
  'Water Management In Tropical Farmlands - A Few Strategies',
  'Best Farmland Asset Management Companies',
  'Dryland Farming: Everything You Need to Know',
  'Unlocking the Potential of Regenerative Agriculture for Sustainable Farming',
  'Exploring Cutting-Edge New Technology in Agriculture',
  'Difference Between Agriculture and Horticulture: Exploring the Key Contrasts',
  'Horticulture Crops: Cultivating the Future of Agriculture',
  'A Comprehensive Look at Different Types of Farming in India',
  'The Advantages of Organic Farming: A Sustainable Future',
  'Discovering Smart Ways for the Best Use of Agricultural Land in India',
  '6 Best fencing for agricultural land in India: Power Fencing and More',
  '4 Modern Bamboo House Designs In Farmhouses: Where Sustainability Meets Simplicity',
  'Plantation Process: 9 Steps to Plant a Tree',
];

const POST_LINKS = [
  'https://www.nimbusagrofarms.in/post/timberland-investment',
  'https://www.nimbusagrofarms.in/post/agriculture-farmland-as-measures-to-control-inflation',
  'https://www.nimbusagrofarms.in/post/how-to-convert-agricultural-land-to-commercial-land',
  'https://www.nimbusagrofarms.in/post/agriculture-land-measurement-in-india',
  'https://www.nimbusagrofarms.in/post/coconut-farming-in-india',
  'https://www.nimbusagrofarms.in/post/managed-farmland-investments',
  'https://www.nimbusagrofarms.in/post/importance-of-van-mahotsav',
  'https://www.nimbusagrofarms.in/post/types-of-agricultural-land-in-india',
  'https://www.nimbusagrofarms.in/post/agriculture-land-registration-charges',
  'https://www.nimbusagrofarms.in/post/agricultural-land-reform-in-india',
  'https://www.nimbusagrofarms.in/post/capital-gains-on-the-sale-of-agricultural-land',
  'https://www.nimbusagrofarms.in/post/water-management-in-tropical-farmlands',
  'https://www.nimbusagrofarms.in/post/best-farmland-asset-management-companies',
  'https://www.nimbusagrofarms.in/post/dryland-farming',
  'https://www.nimbusagrofarms.in/post/regenerative-agriculture',
  'https://www.nimbusagrofarms.in/post/new-technology-in-agriculture',
  'https://www.nimbusagrofarms.in/post/difference-between-agriculture-and-horticulture',
  'https://www.nimbusagrofarms.in/post/horticulture-crops',
  'https://www.nimbusagrofarms.in/post/different-types-of-farming-in-india',
  'https://www.nimbusagrofarms.in/post/advantages-of-organic-farming',
  'https://www.nimbusagrofarms.in/post/best-use-of-agricultural-land-in-india',
  'https://www.nimbusagrofarms.in/post/best-fencing-for-agricultural-land-in-india',
  'https://www.nimbusagrofarms.in/post/bamboo-house-designs-in-farmhouses',
  'https://www.nimbusagrofarms.in/post/plantation-process',
];

export const posts = [...Array(23)].map((_, index) => ({
  id: faker.string.uuid(),
  cover: `/assets/images/covers/cover_${index + 1}.jpg`,
  title: POST_TITLES[index],
  link: POST_LINKS[index],
  createdAt: faker.date.past(),
  view: faker.number.int(99999),
  comment: faker.number.int(99999),
  share: faker.number.int(99999),
  favorite: faker.number.int(99999),
  author: {
    name: faker.person.fullName(),
    avatarUrl: `/assets/images/avatars/avatar_${index + 1}.jpg`,
  },
}));
